const MODE_THUMBNAIL =
  'https://assets.coingecko.com/coins/images/34979/thumb/MODE.jpg?1714561871'
exports.MODE_THUMBNAIL = MODE_THUMBNAIL
const MODE_HOLDER_ROLE_NAME = 'MODE HOLDER'
exports.MODE_HOLDER_ROLE_NAME = MODE_HOLDER_ROLE_NAME
const MIN_BALANCE = 1
exports.MIN_BALANCE = MIN_BALANCE
const MODE_FUNDS_ENDPOINT = 'http://ref.mode.network/funds'
exports.MODE_FUNDS_ENDPOINT = MODE_FUNDS_ENDPOINT
const TYPE_MESSAGE = 1
exports.TYPE_MESSAGE = TYPE_MESSAGE
const TYPE_INTERACTION = 2
exports.TYPE_INTERACTION = TYPE_INTERACTION
